version: '3.6'
services:
    message-app:
        build: ./message-app
        environment:
            - tracing.host=jaeger
        ports:
            - 8080:8080
        links: 
            - jaeger

    user-app:
        build: ./user-app
        environment:
            - tracing.host=jaeger
        ports:
            - 8081:8081
        links: 
            - jaeger

    rest-client:
        build: ./rest-client
        environment:
            - tracing.host=jaeger
            - user/mp-rest/uri=http://user-app:8081
            - message/mp-rest/uri=http://message-app:8080

        ports:
            - 8082:8082
        links: 
            - jaeger
        depends_on:
            - message-app
            - user-app
    jaeger:
        image: jaegertracing/all-in-one:1.23
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14268:14268
